namespace backend.Features.Logistics.DTOs;

public record CreateDispatchRequest(
    string Direction,
    Guid? WarehouseId,
    string? AgreementId,
    string? LotId,
    string? BatchId,
    string? FarmerOrProcessorName,
    string? ProcessorType,
    string? MilletType,
    string? SourceAddress,
    string? DestinationAddress,
    string? TransportResponsibility,
    string? VehicleNumber,
    decimal? VehicleCapacityKg,
    string? DriverName,
    string? DriverPhone,
    decimal TotalQuantityKg,
    DateTime ScheduledDate,
    string? ScheduledStartTime,
    string? ScheduledEndTime,
    string? SpecialInstructions
);

public record DispatchResponse(
    Guid Id,
    string DispatchCode,
    string Direction,
    Guid? WarehouseId,
    string WarehouseName,
    string AgreementId,
    string LotId,
    string BatchId,
    string FarmerOrProcessorName,
    string ProcessorType,
    string MilletType,
    string SourceAddress,
    string DestinationAddress,
    string TransportResponsibility,
    string VehicleNumber,
    decimal VehicleCapacityKg,
    string DriverName,
    string DriverPhone,
    decimal TotalQuantityKg,
    decimal? FinalReceivedQuantityKg,
    decimal? WarehouseStockAfterDispatchKg,
    string Status,
    string WarehouseReceiptStatus,
    DateTime ScheduledDate,
    string ScheduledStartTime,
    string ScheduledEndTime,
    string SpecialInstructions,
    DateTime? DeliveredDate,
    DateTime CreatedAt
);
